// MOHAN file lab — downloads for everything: xlsx, md, txt, code files, pdf (print), csv.
import { parseCsv } from './markdown.js';

export function downloadBlob(blob, name) {
  const a = document.createElement('a');
  a.href = URL.createObjectURL(blob);
  a.download = name;
  document.body.appendChild(a);
  a.click();
  setTimeout(() => { URL.revokeObjectURL(a.href); a.remove(); }, 1500);
}

export function downloadText(text, name, mime = 'text/plain') {
  downloadBlob(new Blob([text], { type: `${mime};charset=utf-8` }), name);
}

export const stamp = () => new Date().toISOString().slice(0, 19).replace(/[:T]/g, '-');

export const CODE_EXT = {
  javascript: 'js', typescript: 'ts', python: 'py', java: 'java', c: 'c', cpp: 'cpp',
  go: 'go', rust: 'rs', ruby: 'rb', php: 'php', html: 'html', css: 'css', json: 'json',
  bash: 'sh', shell: 'sh', sql: 'sql', yaml: 'yml', xml: 'xml', markdown: 'md',
  text: 'txt', csv: 'csv', kotlin: 'kt', swift: 'swift',
};

export function aoaFromTableEl(tableEl) {
  return [...tableEl.rows].map((r) => [...r.cells].map((c) => c.innerText.replace(/\n/g, ' ').trim()));
}

export async function exportAoaToXlsx(aoa, name) {
  const XLSX = await import('xlsx');
  const ws = XLSX.utils.aoa_to_sheet(aoa);
  // auto column widths (rough pass)
  const widths = aoa[0] ? aoa[0].map((_, ci) => Math.min(40, Math.max(8, ...aoa.map((r) => String(r[ci] || '').length + 2)))) : [];
  ws['!cols'] = widths.map((w) => ({ wch: w }));
  const wb = XLSX.utils.book_new();
  XLSX.utils.book_append_sheet(wb, ws, 'MOHAN');
  XLSX.writeFile(wb, name);
}

export async function exportMessageXlsx(containerEl, csvBlocks = []) {
  try {
    let aoa = null;
    const tbl = containerEl && containerEl.querySelector('table');
    if (tbl) aoa = aoaFromTableEl(tbl);
    else if (csvBlocks.length) aoa = parseCsv(csvBlocks[0]);
    if (!aoa || !aoa.length) return false;
    if (aoa.length === 1 && aoa[0].length === 1) return false;
    await exportAoaToXlsx(aoa, `mohan-sheet-${stamp()}.xlsx`);
    return true;
  } catch (e) {
    console.warn('xlsx export failed', e);
    return false;
  }
}

export function exportCsv(csvText) {
  downloadText(csvText, `mohan-data-${stamp()}.csv`, 'text/csv');
}

export function downloadCode(code, lang) {
  const ext = CODE_EXT[lang] || 'txt';
  downloadText(code, `mohan-code-${stamp()}.${ext}`, 'text/plain');
}

// Print-to-PDF: multilingual-perfect (Devanagari & friends) via the browser engine.
export function openPrint(kindLabel, innerHtml) {
  const pr = document.getElementById('print-root');
  if (!pr) return;
  pr.innerHTML = `<div class="doc"><div class="doc-brand"><span class="doc-logo">M</span><div><h1>MOHAN</h1><p>${kindLabel} · ${new Date().toLocaleString()}</p></div></div><div class="doc-body">${innerHtml}</div><footer class="doc-foot">Generated by MOHAN · free multi-model AI</footer></div>`;
  document.body.classList.add('printing');
  const cleanup = () => {
    document.body.classList.remove('printing');
    pr.innerHTML = '';
    window.removeEventListener('afterprint', cleanup);
  };
  window.addEventListener('afterprint', cleanup);
  setTimeout(() => { window.print(); setTimeout(cleanup, 1500); }, 80);
}
